name: deploy_site
on:
  push:
    branches:
      - main
  schedule:
    - cron: '5 16 * * *'

jobs:
  Run-Test-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ghrocker
      - name: Test build
        run: ghrocker --build .
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SENSETHINKACT_UPLOAD_KEY }}
          ARGS: '-av --partial --delete --exclude .well-known'
          SOURCE: '_site/'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: '.well-known'
